### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by celox5801** [loot/skyrimse#60] opened 2018-02-24 20:58 UTC
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1755230/LOOTDebugLog.txt)

**Comment by pStyl3** [comment] 2018-02-25 07:39
> [23:56:33.623828] [info]: Unknown masterlist revision: No masterlist present.

Have you tried to update your masterlist? It's possible, that your issue is the same as in issue loot/loot#882 (although the corresponding line for that issue seems to be missing from your debug log), in which case you should update your Windows with all recommended patches and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.

**Comment by celox5801** [comment] 2018-02-25 12:08
I tried but says you have that update.And i cannot update my masterlist.

**Comment by Ortham** [comment] 2018-02-25 12:15
> And i cannot update my masterlist.

Why not, what's stopping you? There's nothing in your debug log to suggest it even tried to update your masterlist.

**Comment by celox5801** [comment] 2018-02-25 13:24
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1756046/LOOTDebugLog.txt)

There is not because i tried like 15 times reinstalling loot and debug log up there comes from fresh one.When i try uptade my masterlist there is same error ''Something went wrong check debut log''.I am using win 7 if i use win 10 problem will solved?And i am sorry for my english is noot good right :D

**Comment by Ortham** [comment] 2018-02-25 13:31
Delete `C:\Users\esc\AppData\Local\LOOT\Skyrim Special Edition`, it looks like something got corrupted.

**Comment by celox5801** [comment] 2018-02-25 13:52
I tried that too so many times.I deleted everything familiar to loot from my computer and i reinstall skyrim many times.I even tried to launch loot in another computer and same issues happened.

But i say who knows maybe this time works and tried but nothing changed

[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/1756087/LOOTDebugLog.txt)

İ didnt tried download masterlist from here https://raw.githubusercontent.com/loot/skyrim/v0.10/masterlist.yaml
because i cant understand how i download this.

**Comment by Ortham** [comment] 2018-02-25 14:33
You're also getting loot/loot#882, see the fix that's there or in the release notes, readme and FAQs.

**Comment by celox5801** [comment] 2018-02-25 15:00
İ looked there too but i cant understand how to download masterlist from https://raw.githubusercontent.com/loot/skyrim/v0.10/masterlist.yaml this link.

**Comment by Ortham** [comment] 2018-02-25 15:24
If you install the fix from Microsoft, you don't need to manually download the masterlist.

**Comment by celox5801** [comment] 2018-02-25 15:27
I installed the fix.İ did everything else.I am hopeless i guess.:( Thanks for your time.

**Comment by celox5801** [comment] 2018-02-25 15:38
can it be a server problem ?

**Comment by pStyl3** [comment] 2018-03-03 11:08
> [16:50:32.937000] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

This line from your last Debug Log tells us, that your problem is covered in issue 882, as has wrinklyninja already pointed out. Everything stands over there (what happened, why it happened and how it can be fixed).
In short: Update your windows and enable TLS 1.2 support.

> I installed the fix.

What exactly did you do? Did you try to install what is labeled as "EasyFix"?

**Comment by Ortham** [comment] 2018-05-27 07:17
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed as completed by Ortham** 2018-05-27 07:17 UTC
