### ISSUE TITLE
Loot Dont Sort Pluguin

### ISSUE THREAD

**Issue by Oceato** [loot/skyrimse#53] opened 2017-12-02 01:25 UTC
So first, I'm French, so please do not be angry if I speak bad English

My problem is here for 2-3 months, every time I try to sort the plugins, Loot places it in the appropriate loader in the "loot application" but not in NMM. So I have to watch if each plugin is in the right place. It still seems pretty capricious but when you have more than 230 plugins it's not very funny to do every time you install a mod. So do you think you could help me?

I hope you will anser fast 

Oceato

**Comment by Ortham** [comment] 2017-12-02 08:35
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). The logs will help to debug this.

**Comment by Ortham** [comment] 2018-02-08 13:35
Closing this bug report as it looks like it's not a metadata issue, so it's in the wrong repository, and was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be re-filed in the loot/loot issue tracker.

**Closed as completed by Ortham** 2018-02-08 13:35 UTC
Labels: invalid
