### ISSUE TITLE
Skyrim Unlocked load order

### ISSUE THREAD

**Issue by chrisyowyow** [loot/skyrimse#1613] opened 2021-02-23 07:56 UTC
https://www.nexusmods.com/skyrim/mods/69420/ 
https://github.com/Kaenguru-Knobel-Kette/skyrim-unlocked/releases/

I left the LE link bc it says the following:

**Isn't this mod highly incompatible with other mods because it edits so much?

It's simple: You must load this mod at the end of your load order or you will break stuff!
The best place is right before your bashed patch/SkyProc patches. If you follow this advice Skyrim Unlocked will be compatible with pretty much every mod. This includes major overhauls like Epic Gameplay Overhaul, Perkus Maximus and Requiem or quest modifications like Even Better Quest Objectives and Timing is Everything.**

**Comment by sibir-ine** [comment] 2021-02-23 09:36
> https://www.nexusmods.com/skyrim/mods/69420/

Is this for Skyrim LE or Skyrim SE?

**Comment by chrisyowyow** [comment] 2021-02-23 10:10
SE

**Comment by sibir-ine** [comment] 2021-02-25 14:00
@chrisyowyow I think this is a matter of what I mentioned when we were discussing this on Discord; it isn't any more vital that this mod is loaded late than any other mod.

The only sense in which things will "break" is that it will lose a conflict with another mod & loading it after that mod will simply cause that mod to lose the same conflict. This isn't something load order can fix; patches will be required, of which a few appear to be available. Otherwise, it's up to the user which mods' specific edits they value more or can live without.

However, if there are certain mods you feel this mod should load after, feel free to report them.

From comparing this mod to my load order, I can see that this should load after [Even Better Quest Objectives](https://www.nexusmods.com/skyrimspecialedition/mods/159/) as it forwards changes from EBQO, but its changes will be discarded if EBQO loads after. This can be added to the masterlist as it doesn't load after by default.

- [x] Add `after` to `Skyrim Unlocked.esp` for `BetterQuestObjectives.esp`

**Comment by chrisyowyow** [comment] 2021-02-27 12:10
the only mods that should load after unlocked are bash patches and requiem for an indifferent in my LO.

**Comment by sibir-ine** [comment] 2021-02-27 13:11
> 
> 
> the only mods that should load after unlocked are bash patches and requiem for an indifferent in my LO.

Is there a reason for this outside your or the author's preference? Loading Skyrim Unlocked after a mod it conflicts with breaks that mod just as much as it breaks when it's loaded before. It's changes just don't get propagated unless a patch is used for them. That's not enough of a reason to change a plugin's placement, especially not to load it nearly last.

Skyrim Unlocked is fine as it is in `default`, so do you have any suggestions for specific mods it should load after? I've already made note of Even Better Quest Objectives, so I'll definitely add a rule for that.

**Comment by chrisyowyow** [comment] 2021-02-27 15:52
its author's preference, more or less it can brick main story quest if u place it too high in LO which i found out. so yes it should be placed at bottom and not "default" b/c default just places it wherever. ive made the changes to my personal LO and custom masterlist buut.... yea

**Comment by sibir-ine** [comment] 2021-02-27 16:41
> its author's preference, more or less it can brick main story quest if u place it too high in LO which i found out.

The issue is that it can just as easily induce an equally game-breaking bug by being forced to load so late & overwriting another mod. This has to be handled on an individual basis.

> ive made the changes to my personal LO and custom masterlist

If loading it just before dynamic patches like a bashed patch works best for you & you haven't already, you can add a group that's sorted after `Leveled List Modifiers` & before `Dynamic Patches` using the [Groups Editor](https://loot.readthedocs.io/en/latest/app/usage/groups_editor.html) & add Skyrim Unbound to it.

Other than that, I'll add the EBQO load rule & close this issue. Done in 2ee50f9.

**Closed as completed** 2021-02-27 17:08 UTC
